const houses = [
  {
    id: "1",
    title: "Căn hộ SunShine",
    location: "Đường Điện Biên Phủ, phường 22, quận Bình Thạnh",
    price: "20 triệu/tháng",
    image: require("../image/house5.jpg"),
    details: `Đây là căn hộ với đầy đủ tiện nghi có đầy đủ các dịch vụ tiện ích xung quanh`,
    interiors: [
      require("../image/interior1.jpg"),
      require("../image/interior2.jpg"),
      require("../image/interior3.jpg"),
    ],
    time: "10:30pm - 13:00pm",
    date: "29/06/2023",
    username: "devvinland",
  },
  {
    id: "2",
    title: "Căn hộ Đảo Kim Cương",
    location: "Đường Điện Biên Phủ, phường 22, quận Bình Thạnh",
    image: require("../image/house6.jpg"),
    price: "20 triệu/tháng",
    details: `Đây là căn hộ với đầy đủ tiện nghi có đầy đủ các dịch vụ tiện ích xung quanh`,
    interiors: [
      require("../image/interior1.jpg"),
      require("../image/interior2.jpg"),
      require("../image/interior3.jpg"),
    ],
    time: "10:30pm - 13:00pm",
    date: "29/06/2023",
    username: "devvinland",
  },
  {
    id: "3",
    title: "Căn hộ Pearl Plaza",
    location: "Đường Điện Biên Phủ, phường 22, quận Bình Thạnh",
    price: "20 triệu/tháng",
    image: require("../image/house7.jpg"),
    details: `Đây là căn hộ với đầy đủ tiện nghi có đầy đủ các dịch vụ tiện ích xung quanh`,
    interiors: [
      require("../image/interior1.jpg"),
      require("../image/interior2.jpg"),
      require("../image/interior3.jpg"),
    ],
    time: "10:30pm - 13:00pm",
    date: "29/06/2023",
    username: "devvinland",
  },
  {
    id: "4",
    title: "Căn hộ Yuna",
    location: "Đường Điện Biên Phủ, phường 22, quận Bình Thạnh",
    price: "20 triệu/tháng",
    image: require("../image/house8.jpg"),
    details: `Đây là căn hộ với đầy đủ tiện nghi có đầy đủ các dịch vụ tiện ích xung quanh`,
    interiors: [
      require("../image/interior1.jpg"),
      require("../image/interior2.jpg"),
      require("../image/interior3.jpg"),
    ],
    time: "10:30pm - 13:00pm",
    date: "29/06/2023",
    username: "devvinland",
  },
];

export default houses;
